In [38]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import numpy as np

In [39]:
df = pd.read_csv("Advertising.csv")

In [40]:
df = df.iloc[:,1:len(df)]

In [41]:
X = df.drop("sales",axis = 1)
y = df[["sales"]]

In [6]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [8]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [42]:
import statsmodels.api as sm

In [43]:
lm = sm.OLS(y,X)

In [46]:
model.summary()

AttributeError: 'DataFrame' object has no attribute 'summary'

In [45]:
lm = LinearRegression()

In [46]:
model = lm.fit(X,y)

In [47]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

In [48]:
model.intercept_

array([2.93888937])

In [49]:
2.93888937 + 0.04576465*30  + 0.18853002*10 -0.00103749*40

6.15562947

In [50]:
yeni_veri = [[30],[10],[40]]

In [51]:
yeni_veri = pd.DataFrame(yeni_veri).T

In [52]:
yeni_veri

0   1   2
0  30  10  40

In [53]:
print(type(model))

<class 'sklearn.linear_model._base.LinearRegression'>


In [64]:
yeni_veri = pd.DataFrame([[30, 10, 40]],columns=["TV", "radio", "newspaper"])

In [65]:
model.predict(yeni_veri)

array([[6.15562918]])

In [66]:
from sklearn.metrics import mean_squared_error

In [67]:
mean_squared_error(y,model.predict(X))

np.float64(2.784126314510936)

In [68]:
MSE = mean_squared_error(y,model.predict(X))
RMSE = np.sqrt(MSE)
RMSE

np.float64(1.6685701407225697)

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 99)

In [75]:
# train setinin bağımsız değişkenleri
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [76]:
#test setinin bağımsız değişkenleri
X_test.head()

TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [77]:
#train setinin bağımlı değişkenleri burada
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [78]:
#test setinin bağımlı değişkenkerl burada
y_test.head()

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [79]:
lm= LinearRegression()
model = lm.fit(X_train,y_train)

In [88]:
#eğitim(train hatası)
#(cross val edilmemis(daha hatalı))valide edilmemiş hata
np.sqrt(mean_squared_error(y_train,model.predict(X_train)))

np.float64(1.7236824822650751)

In [82]:
#test hatası
np.sqrt(mean_squared_error(y_test,model.predict(X_test)))

np.float64(1.4312783138301637)

In [83]:
# k-katlı cross validation
from sklearn.model_selection import cross_val_score

In [84]:
#train seti 10 barcaya bölünür,9 u önce modek kurulup,dışarda kalan 1 parça elde edildi. hepsine uygulandı , 10 hata elde edildi
cross_val_score(model,X_train,y_train,cv= 10,scoring = "neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [85]:
#train setinin ortalama hatası
#cv ile elde edilmiş mse değeri
np.mean(-cross_val_score(model,X_train,y_train,cv= 10,scoring = "neg_mean_squared_error"))

np.float64(3.3170289742341255)

In [87]:
#cv ile elde edilmiş rmse değeri(daah doğru bir sayı verir)
#train seti özelinde yaptık
np.sqrt(np.mean(-cross_val_score(model,X_train,y_train,cv= 10,scoring = "neg_mean_squared_error")))

np.float64(1.8212712522395245)

In [89]:
#bütün veriyi tek bir veri olarak ele aldı.
np.sqrt(np.mean(-cross_val_score(model,X,y,cv= 10,scoring = "neg_mean_squared_error")))

np.float64(1.7492763126843383)